name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Убедитесь, что указана версия `@v2`

      - name: Set up Python
        uses: actions/setup-python@v2  # Также убедитесь, что указана версия `@v2`
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 11Lab/requirements.txt

      - name: Run tests
        run: |
          pytest 11Lab/test_math_functions.py --junitxml=11Lab/report.xml
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v2  # Версия должна быть указана
        with:
          name: report
          path: 11Lab/report.xml
